apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  configuration.yaml: |
    web:
      host: '0.0.0.0'
      port: {{ .Values.port }}
    databases:
      sqlite:
        path: "/app/db/finance.db"  
        table: "finance"  
    skills:
{{ toYaml .Values.skills | indent 6 }}
    connectors:
      matrix:
        mxid: {{ .Values.botUser | quote }}
        password: {{ .Values.botPassword | quote }}
        rooms:
          "main": {{ .Values.roomId | quote }}
          "escalation_room": {{ .Values.roomEscalationId | quote }}
        homeserver: {{ .Values.homeserver }}
        enable_encryption: True
        store_path: "/app/store/"
        device_name: "bot"
        device_id: "bot"
