environment: production

port: 8080

image:
  repo: web3f/matrixbot
  tag: latest

botUser: "user"
botPassword: "pass"
roomId: "room"
# Rooms to auto-join.
# Note: also add this remove in the skill section bellow.
roomEscalationId1: "room1"
roomEscalationId2: "room2"

homeserver: "https://matrix.web3.foundation"

skills:
- name: eventmanager
  path: /app/skills/skill-eventmanager
- name: eventmanagerack
  path: /app/skills/skill-eventmanager-ack
  escalation_threshold: 3
  escalation_rooms:
    - "room1"
    - "room2"
