environment: production

port: 8080

image:
  repo: web3f/matrixbot
  tag: latest

botUser: "user"
botPassword: "pass"
roomId: "room"
# Note: also add this remove in the skill section bellow.
roomEscalationId: "room"

homeserver: "https://matrix.web3.foundation"

skills:
- name: eventmanager
  path: /app/skills/skill-eventmanager
- name: eventmanagerack
  path: /app/skills/skill-eventmanager-ack
  escalation_room: "room"
  escalation_threshold: 3
