environment: production

port: 8080

image:
  repo: web3f/matrixbot
  tag: latest

botUser: "user"
botPassword: "pass"
roomId: "room"
roomEscalationId: "room"

homeserver: "https://matrix.web3.foundation"

skills:
  alertmanager:
    path: /app/skills/skill-alertmanager
